[package]
name = "testapi"
version = "0.0.0"

[dependencies]
iron = "0.5.*"
router = "*"
rustc-serialize = "*"
diesel = { version = "0.16.0", features = ["postgres"] }
diesel_codegen = { version = "0.16.0", features = ["postgres"] }
dotenv = "0.9.0"